function [val, sdev] = relativeAvgTotalEMG(...
    unassisted_emg, unassisted_time, unassisted_peaks, ...
    assisted_emg, assisted_time, assisted_peaks)

n_waves = length(unassisted_peaks) - 1;
measurements = zeros(n_waves,1);

% Compute the total EMG for each waveform.
for i=1:n_waves
    unassisted_waveform = ...
        unassisted_emg(unassisted_peaks(i):unassisted_peaks(i+1)-1);
    unassisted_times = ...
        unassisted_time(unassisted_peaks(i):unassisted_peaks(i+1)-1);
    
    assisted_waveform = ...
        assisted_emg(assisted_peaks(i):assisted_peaks(i+1)-1);
    assisted_times = ...
        assisted_time(assisted_peaks(i):assisted_peaks(i+1)-1);
    
    measurements(i,1) = ...
        100*(trapz(unassisted_times, unassisted_waveform) - ...
        trapz(assisted_times, assisted_waveform)) / ...
        trapz(unassisted_times, unassisted_waveform); 
end

% Return the mean and standard deviation. 
val = mean(measurements);
sdev = std(measurements);